### ISSUE TITLE
[Bug] Adding Hunters crashes server

### ISSUE THREAD

**Issue by LunarAvenger** [YTG1234/manhunt-fabric#16]
## Describe the bug
After installing the required Fabric, Fabric API, Kotlin, and Manhunt mod. 
Start game, attempt to use "/hunters add Huntername" 
Server crashes. 

## Expected behaviour
I expected to add my friend as a hunter, not to crash. 
## System Information (please fill in the following details)
 - Fabric Loader Version: 1.17.1 (0.11.6) 
 - Mod Version: manhunt-2.0.2
 - Fabric API Version: api-0.37.1+1.17

## Additional context
This is being attempted on an Aternos Server, though from my understanding that shouldn't be an issue, as your mod is in the approved list.

**Comment by YTG1234** [comment]
Thank you for the report. I wasn't aware that my mod was approved by Aternos.

When adding a hunter, many things could fail. Can you obtain and send a crash report?

**Comment by ghost** [comment]
> Thank you for the report. I wasn't aware that my mod was approved by Aternos.
> 
> When adding a hunter, many things could fail. Can you obtain and send a crash report?

plz make this mod a 1.17.1 version

**Comment by YTG1234** [comment]
> > Thank you for the report. I wasn't aware that my mod was approved by Aternos.
> > When adding a hunter, many things could fail. Can you obtain and send a crash report?
> 
> plz make this mod a 1.17.1 version

I don't hard-require any specific version of Minecraft [a](https://gitlab.com/ytg123-mods/manhunt-fabric/-/blob/main/src/main/resources/fabric.mod.json#L16-17)[ny](https://gitlab.com/ytg123-mods/manhunt-fabric/-/blob/main/manhunt-api/src/main/resources/fabric.mod.json#L20-22)[where](https://gitlab.com/ytg123-mods/manhunt-fabric/-/blob/main/manhunt-base/src/main/resources/fabric.mod.json#L38-44). Does this not already work on 1.17.1?

If it doesn't, open a *new issue* (preferably on gitlab.com instead of here) and upload any and all crash logs and information.

**Comment by LunarAvenger** [comment]
Here is the crash log as requested, I finally had the oppertunity to get my friend into the server with me.

https://mclo.gs/LBqZzBd

as well as a copy and paste of the error section that is at the end which I believe is the important part, the rest is simply the loading in, me and my buddy logging in, the free to play server being laggy, and then the crash. 

Even when it isn't laggy, this crash occurs. 


<html>
<body>


[00:18:22] [Server thread/ERROR]: Encountered an unexpected exception
--
207 | java.lang.NoSuchMethodError: 'boolean net.minecraft.class_3222.method_5758(int, net.minecraft.class_1799)'
208 | at io.github.ytg1234.manhunt.command.HuntersCommand.executeAdd(HuntersCommand.java:107) ~[30433a0d-16f8-4944-bae5-9033ac98302a.jar:?]
209 | at io.github.ytg1234.manhunt.command.HuntersCommand.access$executeAdd(HuntersCommand.java:28) ~[30433a0d-16f8-4944-bae5-9033ac98302a.jar:?]
210 | at io.github.ytg1234.manhunt.command.HuntersCommand$register$1$2$2$1.invoke(HuntersCommand.java:39) ~[30433a0d-16f8-4944-bae5-9033ac98302a.jar:?]
211 | at io.github.ytg1234.manhunt.command.HuntersCommand$register$1$2$2$1.invoke(HuntersCommand.java:28) ~[30433a0d-16f8-4944-bae5-9033ac98302a.jar:?]
212 | at mc.aegis.AegisCommandBuilder$sam$com_mojang_brigadier_Command$0.run(AegisCommandBuilder.java) ~[e473b242-d4f4-4023-aa5e-1903c4d96fe5.jar:?]
213 | at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[intermediary-server.jar:?]
214 | at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[intermediary-server.jar:?]
215 | at net.minecraft.class_2170.method_9249(class_2170.java:251) ~[intermediary-server.jar:?]
216 | at net.minecraft.class_3244.method_14370(class_3244.java:1222) ~[intermediary-server.jar:?]
217 | at net.minecraft.class_3244.method_31286(class_3244.java:1206) ~[intermediary-server.jar:?]
218 | at net.minecraft.class_3244.method_12048(class_3244.java:1189) ~[intermediary-server.jar:?]
219 | at net.minecraft.class_2797.method_12115(class_2797.java:30) ~[intermediary-server.jar:?]
220 | at net.minecraft.class_2797.method_11054(class_2797.java:7) ~[intermediary-server.jar:?]
221 | at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
222 | at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
223 | at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
224 | at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
225 | at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
226 | at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
227 | at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
228 | at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
229 | at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
230 | at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[intermediary-server.jar:?]
231 | at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[intermediary-server.jar:?]
232 | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
233 | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
234 | at java.lang.Thread.run(Thread.java:831) [?:?]
235 | [00:18:22] [Server thread/ERROR]: This crash report has been saved to: /server/./crash-reports/crash-2021-08-11_00.18.22-server.txt
236 | [00:18:22] [Server thread/INFO]: Stopping server


</body>
</html>

**Comment by YTG1234** [comment]
This seems to have been fixed by #17. There is no release yet on CF/MR but you can download a CI-built file from [here](https://gitlab.com/ytg123-mods/manhunt-fabric/-/jobs/1478802869/artifacts/download).

**Comment by HuiNight-TECHO** [comment]
> > > Thank you for the report. I wasn't aware that my mod was approved by Aternos.
> > > When adding a hunter, many things could fail. Can you obtain and send a crash report?
> > 
> > 
> > plz make this mod a 1.17.1 version
> 
> I don't hard-require any specific version of Minecraft [a](https://gitlab.com/ytg123-mods/manhunt-fabric/-/blob/main/src/main/resources/fabric.mod.json#L16-17)[ny](https://gitlab.com/ytg123-mods/manhunt-fabric/-/blob/main/manhunt-api/src/main/resources/fabric.mod.json#L20-22)[where](https://gitlab.com/ytg123-mods/manhunt-fabric/-/blob/main/manhunt-base/src/main/resources/fabric.mod.json#L38-44). Does this not already work on 1.17.1?
> 
> If it doesn't, open a _new issue_ (preferably on gitlab.com instead of here) and upload any and all crash logs and information.

gitlab.com/ytg123-mods/manhunt-fabric/-/issues/2

**Comment by LunarAvenger** [comment]
> This seems to have been fixed by #17. There is no release yet on CF/MR but you can download a CI-built file from [here](https://gitlab.com/ytg123-mods/manhunt-fabric/-/jobs/1478802869/artifacts/download).

That requires me to not be running it on a free server that I could manually add files to? 

I see what I think is the issue. The only version I can add via Aternos is 2.0.2.... not 2.0.3... grrr. I suppose I could play manhunt on 1.16 and it would just work.
